### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by benfoxall** [benfoxall/JumboPi#2]
- [x] check broadcasting with static assigned addresses
- [x] buy [more routers](http://www.amazon.co.uk/gp/product/B0000E5SES?keywords=GS108&qid=1442784081&ref_=sr_1_1&sr=8-1)
- [x] powerwheel from raspian
- [x] implement debug mode
- [x] shutdown from OF
- [x] [startup](http://raspberrywebserver.com/serveradmin/run-a-script-on-start-up.html) [2](http://www.raspberry-projects.com/pi/pi-operating-systems/raspbian/auto-running-programs)
- [ ] write image

---

Approach:
- static assign `10.0.0.50` for common build
- plug one by one, number `10.0.0.1` -> `10.0.0.20`

**Comment by benfoxall** [comment]
/etc/network/interfaces

```
auto lo
iface lo inet loopback

#auto eth0
#allow-hotplug eth0
#iface eth0 inet manual

iface eth0 inet static
address 10.0.0.40
netmask 255.255.255.0
#network 10.0.0.1
broadcast 10.0.0.255
#gateway [your gateway]

auto wlan0
allow-hotplug wlan0
iface wlan0 inet manual
wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf

auto wlan1
allow-hotplug wlan1
iface wlan1 inet manual
wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf
```

**Comment by benfoxall** [comment]
cloning cards - http://computers.tutsplus.com/articles/how-to-clone-raspberry-pi-sd-cards-using-the-command-line-in-os-x--mac-59911
